import { Router } from 'express';
import { authenticatedHandler, requireUser } from '../auth/middleware.js';
import * as agentsController from '../controllers/agents-controller.js';
import * as agentsLifecycleController from '../controllers/agents-lifecycle-controller.js';
import { getAutomationDiagnostics } from '../controllers/automation-diagnostics-controller.js';
import * as agentMcpController from '../controllers/agent-mcp-controller.js';
import * as mcpConnectionsController from '../controllers/mcp-connections-controller.js';
import { importAgentCatalogMcpServer, reimportAgentCatalogMcpServer } from '../controllers/catalog-controller.js';
import * as agentSkillsController from '../controllers/agent-skills-controller.js';
import * as serviceIdentitiesController from '../controllers/service-identities-controller.js';
import * as automationTemplatesController from '../controllers/automation-templates-controller.js';
import { requirePublicAgentRoute } from '../controllers/public-agent-visibility.js';
import * as agentNativeToolsController from '../controllers/agent-native-tools-controller.js';

export const agentsRouter = Router();
const authed = authenticatedHandler;
const publicAgentVisibility = authed(requirePublicAgentRoute);

agentsRouter.get('/workspaces/:workspaceId/agents', requireUser, authed(agentsController.listAgents));
agentsRouter.post('/workspaces/:workspaceId/agents', requireUser, authed(agentsController.createAgent));
agentsRouter.get('/workspaces/:workspaceId/catalog/native-tools', requireUser, authed(agentNativeToolsController.listNativeTools));
agentsRouter.put('/workspaces/:workspaceId/agents/:agentId/native-tools/:toolId', requireUser, publicAgentVisibility, authed(agentNativeToolsController.grantNativeTool));
agentsRouter.delete('/workspaces/:workspaceId/agents/:agentId/native-tools/:toolId', requireUser, publicAgentVisibility, authed(agentNativeToolsController.revokeNativeTool));
agentsRouter.get('/workspaces/:workspaceId/automation-templates', requireUser, authed(automationTemplatesController.list));
agentsRouter.post('/workspaces/:workspaceId/automation-templates/:templateId/install', requireUser, authed(automationTemplatesController.install));
agentsRouter.post('/workspaces/:workspaceId/automation-templates/:templateId/activate', requireUser, authed(automationTemplatesController.activate));
agentsRouter.get('/workspaces/:workspaceId/service-identities', requireUser, authed(serviceIdentitiesController.list));
agentsRouter.post('/workspaces/:workspaceId/service-identities', requireUser, authed(serviceIdentitiesController.create));
agentsRouter.patch('/workspaces/:workspaceId/service-identities/:serviceIdentityId', requireUser, authed(serviceIdentitiesController.patch));
agentsRouter.get('/workspaces/:workspaceId/agents/:agentId/mcp/servers', requireUser, publicAgentVisibility, authed(agentMcpController.listServers));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/mcp/servers', requireUser, publicAgentVisibility, authed(agentMcpController.createServer));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/mcp/servers/import', requireUser, publicAgentVisibility, authed(importAgentCatalogMcpServer));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/reimport', requireUser, publicAgentVisibility, authed(reimportAgentCatalogMcpServer));
agentsRouter.get('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/tools', requireUser, publicAgentVisibility, authed(agentMcpController.listTools));
agentsRouter.patch('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/tools/:toolName', requireUser, publicAgentVisibility, authed(agentMcpController.patchTool));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/test-connection', requireUser, publicAgentVisibility, authed(agentMcpController.testServer));
agentsRouter.patch('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId', requireUser, publicAgentVisibility, authed(agentMcpController.patchServer));
agentsRouter.delete('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId', requireUser, publicAgentVisibility, authed(agentMcpController.removeServer));
agentsRouter.get('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/connection', requireUser, publicAgentVisibility, authed(mcpConnectionsController.getMcpConnectionStatus));
agentsRouter.put('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/connection', requireUser, publicAgentVisibility, authed(mcpConnectionsController.putMcpConnection));
agentsRouter.delete('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/connection', requireUser, publicAgentVisibility, authed(mcpConnectionsController.deleteMcpConnectionStatus));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/mcp/servers/:serverId/connection/verify', requireUser, publicAgentVisibility, authed(mcpConnectionsController.verifyMcpConnectionStatus));
agentsRouter.get('/workspaces/:workspaceId/agents/:agentId/skills', requireUser, publicAgentVisibility, authed(agentSkillsController.listSkills));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/skills', requireUser, publicAgentVisibility, authed(agentSkillsController.createSkill));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/skills/import', requireUser, publicAgentVisibility, authed(agentSkillsController.importSkill));
agentsRouter.get('/workspaces/:workspaceId/agents/:agentId/skills/:skillId', requireUser, publicAgentVisibility, authed(agentSkillsController.getSkill));
agentsRouter.patch('/workspaces/:workspaceId/agents/:agentId/skills/:skillId', requireUser, publicAgentVisibility, authed(agentSkillsController.patchSkill));
agentsRouter.delete('/workspaces/:workspaceId/agents/:agentId/skills/:skillId', requireUser, publicAgentVisibility, authed(agentSkillsController.removeSkill));
agentsRouter.post('/workspaces/:workspaceId/agents/:agentId/skills/:skillId/reimport', requireUser, publicAgentVisibility, authed(agentSkillsController.reimportSkill));
agentsRouter.get('/workspaces/:workspaceId/automation/diagnostics', requireUser, authed(getAutomationDiagnostics));
agentsRouter.get('/agents/:agentId', requireUser, publicAgentVisibility, authed(agentsController.getAgent));
agentsRouter.post('/agents/:agentId/duplicate', requireUser, publicAgentVisibility, authed(agentsLifecycleController.duplicateAgent));
agentsRouter.patch('/agents/:agentId', requireUser, publicAgentVisibility, authed(agentsController.updateAgent));
agentsRouter.delete('/agents/:agentId', requireUser, publicAgentVisibility, authed(agentsLifecycleController.deleteAgent));
agentsRouter.get('/agents/:agentId/versions', requireUser, publicAgentVisibility, authed(agentsController.listAgentVersions));
agentsRouter.post('/agents/:agentId/versions', requireUser, publicAgentVisibility, authed(agentsController.createAgentVersion));
agentsRouter.post('/agents/:agentId/versions/:versionId/restore', requireUser, publicAgentVisibility, authed(agentsController.restoreAgentVersion));
