import { Router } from 'express';
import { authenticatedHandler, requireActor } from '../auth/middleware.js';
import * as workflowsController from '../controllers/workflows-controller.js';
import * as workflowSchedulesController from '../controllers/workflow-schedules-controller.js';
import * as workflowExecutionsController from '../controllers/workflow-executions-controller.js';
import * as workflowReportsController from '../controllers/workflow-reports-controller.js';

export const workflowsRouter = Router();
const authed = authenticatedHandler;

workflowsRouter.get('/workspaces/:workspaceId/workflows', requireActor(['user', 'externalIntegration']), authed(workflowsController.listWorkflows));
workflowsRouter.post('/workspaces/:workspaceId/workflows', requireActor(['user']), authed(workflowsController.createWorkflow));
workflowsRouter.get('/workspaces/:workspaceId/workflow-schedules', requireActor(['user']), authed(workflowSchedulesController.listWorkspaceWorkflowSchedules));
workflowsRouter.post('/workspaces/:workspaceId/workflow-schedules', requireActor(['user']), authed(workflowSchedulesController.createWorkflowScheduleForWorkspace));
workflowsRouter.post('/workspaces/:workspaceId/workflow-schedules/preview', requireActor(['user']), authed(workflowSchedulesController.previewWorkflowSchedule));
workflowsRouter.get('/workspaces/:workspaceId/approvals', requireActor(['user']), authed(workflowSchedulesController.listWorkspaceApprovalInbox));
workflowsRouter.get('/workspaces/:workspaceId/workflow-options', requireActor(['user']), authed(workflowsController.listWorkflowOptions));
workflowsRouter.get('/workspaces/:workspaceId/mcp/servers', requireActor(['user']), authed(workflowsController.listWorkflowMcpServersForWorkspace));
workflowsRouter.post('/workspaces/:workspaceId/mcp/servers', requireActor(['user']), authed(workflowsController.createWorkflowMcpServerForWorkspace));
workflowsRouter.patch('/workspaces/:workspaceId/mcp/servers/:serverId', requireActor(['user']), authed(workflowsController.updateWorkflowMcpServerForWorkspace));
workflowsRouter.delete('/workspaces/:workspaceId/mcp/servers/:serverId', requireActor(['user']), authed(workflowsController.deleteWorkflowMcpServerForWorkspace));
workflowsRouter.post('/workspaces/:workspaceId/mcp/servers/:serverId/test-connection', requireActor(['user']), authed(workflowsController.testWorkflowMcpServerConnectionForWorkspace));
workflowsRouter.get('/workspaces/:workspaceId/mcp/servers/:serverId/tools', requireActor(['user']), authed(workflowsController.listWorkflowMcpServerToolsForWorkspace));
workflowsRouter.patch('/workspaces/:workspaceId/mcp/servers/:serverId/tools/:toolName', requireActor(['user']), authed(workflowsController.updateWorkflowMcpToolForWorkspace));
workflowsRouter.get('/workflows/:workflowId', requireActor(['user', 'externalIntegration']), authed(workflowsController.getWorkflow));
workflowsRouter.patch('/workflows/:workflowId', requireActor(['user']), authed(workflowsController.updateWorkflow));
workflowsRouter.delete('/workflows/:workflowId', requireActor(['user']), authed(workflowsController.deleteWorkflow));
workflowsRouter.patch('/workflow-schedules/:scheduleId', requireActor(['user']), authed(workflowSchedulesController.updateWorkflowSchedule));
workflowsRouter.delete('/workflow-schedules/:scheduleId', requireActor(['user']), authed(workflowSchedulesController.deleteWorkflowSchedule));
workflowsRouter.get('/workflows/:workflowId/sessions', requireActor(['user']), authed(workflowsController.listSessions));
workflowsRouter.post('/workflows/:workflowId/sessions', requireActor(['user', 'externalIntegration']), authed(workflowsController.createSession));
workflowsRouter.post('/workflow-sessions/:sessionId/messages', requireActor(['user', 'externalIntegration']), authed(workflowsController.postMessage));
workflowsRouter.get('/workflow-executions/:executionId', requireActor(['user', 'externalIntegration']), authed(workflowExecutionsController.getWorkflowExecution));
workflowsRouter.get('/workflow-executions/:executionId/stream', requireActor(['user', 'externalIntegration']), authed(workflowExecutionsController.streamWorkflowExecution));
workflowsRouter.post('/workflow-executions/:executionId/cancel', requireActor(['user']), authed(workflowExecutionsController.cancelWorkflowExecution));
workflowsRouter.post('/workflow-executions/:executionId/resume', requireActor(['user']), authed(workflowExecutionsController.resumeWorkflowExecutionController));
workflowsRouter.get('/workflow-reports/:reportId', requireActor(['user', 'externalIntegration']), authed(workflowReportsController.getWorkflowReportMetadata));
workflowsRouter.get('/workflow-reports/:reportId/download', requireActor(['user', 'externalIntegration']), authed(workflowReportsController.downloadWorkflowReport));
