import { dateTime, JsonSchema, jsonObject, pageOf, schemaRef, stringArray, uuid } from './schema-types.js';

export function buildCatalogSchemas(): Record<string, JsonSchema> {
  return {
    CatalogBinding: { type: 'object', required: ['id', 'artifactKind', 'adapterType', 'adapterBasePath', 'syncStatus'], properties: { id: uuid, artifactKind: { type: 'string', enum: ['mcp_server', 'agent_skill'] }, adapterType: { type: 'string' }, adapterBasePath: { type: 'string' }, syncStatus: { type: 'string', enum: ['pending', 'syncing', 'ready', 'error'] }, lastSyncAt: dateTime, lastSyncError: { type: 'string' } }, additionalProperties: false },
    CatalogSource: { type: 'object', required: ['id', 'workspaceId', 'displayName', 'baseUrl', 'authType', 'credentialConfigured', 'networkRoute', 'enabled', 'managementMode', 'bindings'], properties: { id: uuid, workspaceId: uuid, displayName: { type: 'string' }, baseUrl: { type: 'string', format: 'uri' }, authType: { type: 'string', enum: ['none', 'bearer_token', 'custom_header'] }, credentialConfigured: { type: 'boolean' }, authHeaderName: { type: 'string' }, networkRoute: { type: 'string', enum: ['direct', 'connector'] }, enabled: { type: 'boolean' }, managementMode: { type: 'string', enum: ['workspace', 'bootstrap'] }, bindings: { type: 'array', items: schemaRef('CatalogBinding') }, createdAt: dateTime, updatedAt: dateTime }, additionalProperties: false },
    CatalogSourceManagementCapabilities: { type: 'object', required: ['workspaceManagedSourcesEnabled', 'supportedNetworkRoutes'], properties: { workspaceManagedSourcesEnabled: { type: 'boolean' }, supportedNetworkRoutes: { type: 'array', items: { type: 'string', enum: ['direct'] } } }, additionalProperties: false },
    CatalogSourceList: { type: 'object', required: ['items', 'capabilities'], properties: { items: { type: 'array', items: schemaRef('CatalogSource') }, capabilities: schemaRef('CatalogSourceManagementCapabilities') }, additionalProperties: false },
    CatalogSourceResponse: { type: 'object', required: ['source'], properties: { source: schemaRef('CatalogSource') }, additionalProperties: false },
    CatalogConfigurationField: { type: 'object', required: ['name', 'location', 'required', 'secret', 'format'], properties: { name: { type: 'string' }, location: { type: 'string', enum: ['url', 'header'] }, headerName: { type: 'string' }, required: { type: 'boolean' }, secret: { type: 'boolean' }, format: { type: 'string', enum: ['string', 'number', 'boolean'] }, description: { type: 'string' }, default: { type: 'string' }, fixedValue: { type: 'string' }, placeholder: { type: 'string' }, choices: stringArray }, additionalProperties: false },
    CatalogRemoteEndpoint: { type: 'object', required: ['type', 'url'], properties: { type: { type: 'string', enum: ['streamable-http'] }, url: { type: 'string' }, supported: { type: 'boolean' }, requiresConfiguration: { type: 'boolean' }, supportedCredentialModes: { type: 'array', items: { type: 'string', enum: ['none', 'workspace', 'individual'] } }, recommendedCredentialMode: { type: 'string', enum: ['none', 'workspace', 'individual'] }, headerNames: stringArray, secretHeaderNames: stringArray, configurationFields: { type: 'array', items: schemaRef('CatalogConfigurationField') } }, additionalProperties: true },
    CatalogArtifact: { type: 'object', required: ['id', 'workspaceId', 'sourceId', 'bindingId', 'artifactKind', 'name', 'description', 'version', 'digest', 'metadata', 'compatible', 'remoteEndpoints'], properties: { id: uuid, workspaceId: uuid, sourceId: uuid, bindingId: uuid, artifactKind: { type: 'string', enum: ['mcp_server', 'agent_skill'] }, name: { type: 'string' }, title: { type: 'string' }, description: { type: 'string' }, version: { type: 'string' }, digest: { type: 'string', pattern: '^sha256:' }, metadata: jsonObject, compatible: { type: 'boolean' }, incompatibilityReason: { type: 'string' }, remoteEndpoints: { type: 'array', items: schemaRef('CatalogRemoteEndpoint') }, publishedAt: dateTime, upstreamUpdatedAt: dateTime }, additionalProperties: false },
    CatalogArtifactPage: pageOf('CatalogArtifact'),
    CatalogArtifactResponse: { type: 'object', required: ['artifact'], properties: { artifact: schemaRef('CatalogArtifact') }, additionalProperties: false },
    AgentMcpTool: { type: 'object', required: ['name', 'serverId', 'alias', 'capability', 'enabled', 'reviewState', 'riskLevel', 'autoAllowed'], properties: { name: { type: 'string' }, serverId: uuid, alias: { type: 'string' }, description: { type: 'string' }, capability: { type: 'string', enum: ['read', 'write'] }, enabled: { type: 'boolean' }, reviewState: { type: 'string', enum: ['pending', 'approved', 'rejected'] }, riskLevel: { type: 'string', enum: ['read_only', 'non_destructive_write', 'high_risk', 'destructive'] }, autoAllowed: { type: 'boolean' } }, additionalProperties: false },
    AgentMcpServer: { type: 'object', required: ['id', 'name', 'url', 'type', 'enabled', 'isSystem', 'canDelete', 'canEditConnection', 'canToggle', 'authType', 'credentialMode', 'revision', 'targetConstraints', 'publicHeaders', 'connectionStatus', 'tools'], properties: { id: uuid, name: { type: 'string' }, url: { type: 'string', format: 'uri' }, type: { type: 'string', enum: ['mcp'] }, enabled: { type: 'boolean' }, isSystem: { type: 'boolean' }, canDelete: { type: 'boolean' }, canEditConnection: { type: 'boolean' }, canToggle: { type: 'boolean' }, authType: { type: 'string', enum: ['none', 'bearer_token', 'custom_header'] }, credentialMode: { type: 'string', enum: ['none', 'workspace', 'individual'] }, authHeaderName: { type: 'string' }, authHeaderPrefix: { type: 'string' }, agentId: uuid, revision: { type: 'integer' }, targetConstraints: jsonObject, provenance: jsonObject, endpointConfiguration: jsonObject, integrationProfileId: { type: 'string' }, integrationProfileVersion: { type: 'integer', minimum: 1 }, publicHeaders: { type: 'object', additionalProperties: { type: 'string' } }, connectionStatus: { type: 'string', enum: ['unknown', 'ok', 'error'] }, lastDiscoveryAt: dateTime, lastDiscoveryError: { type: 'string', nullable: true }, tools: { type: 'array', items: schemaRef('AgentMcpTool') } }, additionalProperties: false },
    AgentMcpServerList: { type: 'object', required: ['items'], properties: { items: { type: 'array', items: schemaRef('AgentMcpServer') } }, additionalProperties: false },
    AgentMcpServerResponse: { type: 'object', required: ['server'], properties: { server: schemaRef('AgentMcpServer') }, additionalProperties: false },
    AgentMcpToolList: { type: 'object', required: ['items'], properties: { items: { type: 'array', items: schemaRef('AgentMcpTool') } }, additionalProperties: false },
    AgentMcpToolResponse: { type: 'object', required: ['tool'], properties: { tool: schemaRef('AgentMcpTool') }, additionalProperties: false },
    AgentMcpConnectionTestResponse: { type: 'object', required: ['result'], properties: { result: {
      type: 'object', required: ['server_id', 'server_name', 'server_url', 'connection_status', 'last_discovery_at', 'discovered_tool_count', 'discovered_tools'],
      properties: {
        server_id: uuid, server_name: { type: 'string' }, server_url: { type: 'string', format: 'uri' },
        connection_status: { type: 'string', enum: ['ok', 'error'] }, last_discovery_at: dateTime,
        discovered_tool_count: { type: 'integer', minimum: 0 }, discovered_tools: stringArray, error: { type: 'string' }
      }, additionalProperties: false
    } }, additionalProperties: false },
    AgentSkill: { type: 'object', required: ['id', 'name', 'description', 'enabled', 'revision', 'contentDigest', 'source', 'files'], properties: { id: uuid, name: { type: 'string' }, description: { type: 'string' }, enabled: { type: 'boolean' }, revision: { type: 'integer' }, contentDigest: { type: 'string', pattern: '^sha256:' }, source: jsonObject, files: { type: 'array', items: jsonObject } }, additionalProperties: false },
    AgentSkillList: { type: 'object', required: ['items'], properties: { items: { type: 'array', items: schemaRef('AgentSkill') }, canEdit: { type: 'boolean' } }, additionalProperties: false },
    AgentSkillResponse: { type: 'object', required: ['skill'], properties: { skill: schemaRef('AgentSkill') }, additionalProperties: false },
    McpConnection: { type: 'object', required: ['serverId', 'credentialMode', 'status', 'managementScope', 'canManage', 'authType'], properties: { serverId: uuid, credentialMode: { type: 'string', enum: ['workspace', 'individual'] }, status: { type: 'string', enum: ['missing', 'connected', 'error'] }, managementScope: { type: 'string', enum: ['workspace', 'individual'] }, canManage: { type: 'boolean' }, authType: { type: 'string', enum: ['bearer_token', 'custom_header'] }, action: { type: 'string', enum: ['connect_mcp_server', 'verify_mcp_server'] }, errorCode: { type: 'string' }, verifiedAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } }, additionalProperties: false },
    McpConnectionResponse: { type: 'object', required: ['connection'], properties: { connection: schemaRef('McpConnection') }, additionalProperties: false }
  };
}
